### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by YoLieR** [fable-compiler/fable-suave-scaffold#102]
Hey together,

when I checkout the repo and run `build.cmd run` everything builds fine but when I then try to login into the sample application I get the following error on the console:

```
[HPM] Error occurred while trying to proxy request /api/users/login from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://node
js.org/api/errors.html#errors_common_system_errors)
```

The build output states the the server was started on port 61225 (not 8085 as specified in `Server/Server.fs`).

```
...
Finished Target: InstallClient                                           
Starting Target: Run (==> InstallClient)                                 
C:\Users\X\AppData\Local\dotnetcore\dotnet.exe fable npm-run start 
C:\Users\X\AppData\Local\dotnetcore\dotnet.exe watch run           
Fable server started on port 61225                                      
CWD: C:\Users\sschmid\Desktop\fable-suave-scaffold\src\Client            
cmd /C npm run start                                                     
watch : Started
...                                                          
```

The client also outputs the error:  
`POST http://localhost:8080/api/users/login 504 (Gateway Timeout)`

I've already tried to rewire the ports of the webpack devserver proxy and the suave server but that didn't help.

Did anyone else encounter this problem? Or Do you have an idea on how to fix it?

Thanks!

**Comment by alfonsogarciacaro** [comment]
Hi @YoLieR! The Fable server on port 61225 is just to compile the JS files and it's not related to the app, so it must be something else. I haven't heard of anyone with port issues, but I'll try to see if I can reproduce.

**Comment by haf** [comment]
@YoLieR You probably have Suave listening on another interface that either localhost or the IP you're proxying to.

**Comment by alfonsogarciacaro** [comment]
I'm closing this for now, please feel free to reopen if you still have problems.

**Comment by adrianboyko** [comment]
I've just done a first-time install of the SAFE Stack using the instructions at https://safe-stack.github.io/docs/quickstart/ and I get exactly the same results described by @YoLieR. Any suggestions on how to diagnose this problem?

**Comment by isaacabraham** [comment]
@adrianboyko It might be worth opening an issue in the safe template repo rather than here. What's the exact template options you used with the SAFE template? The ports should be already linked together.
