### ISSUE TITLE
After adding a book, DOM <> Model is inconsistent

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/fable-suave-scaffold#107]
I have filled the three fields, then pressed add twice.

The first click correctly added the new book, the second click failed as seen in the screenshot:

![image](https://cloud.githubusercontent.com/assets/4236651/26030958/95c8d72c-3863-11e7-8cee-4dd67e8f2e60.png)

This is the last message from the console:
![image](https://cloud.githubusercontent.com/assets/4236651/26030970/044ad22c-3864-11e7-829c-41fa5331ad2c.png)

There seems to be an inconsistency between the actual DOM and the model, in the model, the three textboxes are empty, but in the dom, they contain the previous values.

This occurs in both Chrome and Edge.

**Comment by et1975** [comment]
Short story: 
setting `Value` messes with cursor position and selection and can't keep up with automation.

Longish story: 
`DefaultValue` + `OnChange`  syncs up view -> model, while `Value` syncs view -> model -> view. It would have been ideal to be able  to use `Value` but in practice, setting it resets *everything* in the input box, including cursor position and selection highlighting as these two are not exposed as state of the element. 
In another twist, model->view sync is throttled for by elmish-react to 60fps (with every update resulting in a new frame) tops, so if automation is used to interact with the form, rendered elements may not have what a script expects it to have at certain point even though *the model* under the hood is up to date. 

Specifically about the observed situation:
One way to look at this, is by asking the question "Should I reuse the UI elements for every new entry?". If that's the desired behavior, then the correct solution would be to reset the form upon submission.
The alternative may be giving the model a transient identity (a guid) and binding that as part of the view to `Id` prop. `Id` prop is a hint for the VDOM reconciler that would tell it to treat this element as a new an unrelated once the `Id` has changed, even though it's in the same place in the hierarchy.

**Comment by 0x53A** [comment]
thank you for that longish explanation, I can reproduce the issues with the cursor.


I've seen a few other Fable |> React demos, which also used ``Value``, so basically I can assume that these are all bugs?

Shouldn't that behaviour be considered a bug and reported upstream? It at the very least isn't intuitive.

For this specific case, the question is what the user-visible behaviour should be - should the three fields be cleared after a submission, or should they keep their previous values?

The first option "feels cleaner", but in an actual app, the second may be better for the user, for example if he wants to add multiple books from the same author, he doesn't need to always re-fill that field.
