### ISSUE TITLE
Build breaks after there recent Fable migration to paket/yarn from npm on Mac 

### ISSUE THREAD

**Issue by cotyar** [fable-compiler/fable-suave-scaffold#110]
### Description

Build breaks after there recent Fable migration to paket/yarn from npm on Mac 

### Repro steps

./build.sh run 
fails with:

> dotnet fable npm-run start
> ﻿dotnet watch run
> ﻿No executable found matching command "dotnet-watch"
> ERROR: Cannot find Fable.Compiler package. Please make sure it's been added to `paket.dependencies`.

I've updated my Client.proj and Server.proj according to the latest examples but it didn't help very much.
Looks like something is wrong with the build command

**Comment by alfonsogarciacaro** [comment]
Should be fixed by #111
