### ISSUE TITLE
Can't get hot reloading to work

### ISSUE THREAD

**Issue by piaste** [fable-compiler/fable-suave-scaffold#113]
### Description

Editing and saving either one of the client-side `.fs` files or the `Client.fsproj` files does not trigger a recompile / refresh.

The default `fable` template for the `dotnet` CLI, meanwhile, hot-recompiles correctly.

### Repro steps

This works (change a line in `App.fs` and it recompiles instantly):
1. `dotnet new -i Fable.Template::*`
2. `dotnet new fable -n basicTemplate`
3. `yarn install`
4. `dotnet restore`
5. `dotnet fable webpack-dev-server`

This one does not:
1. `git clone https://github.com/fable-compiler/fable-suave-scaffold`
2. `sh ./build.sh run`

### Known workarounds

None so far, I've fiddled with `webpack.config.js`, trying to make it as similar to the one from the basic template as possible, without success. I tried adding a plain Javascript file to the project (with a corresponding separate `entry` value in `webpack.config.js`) and that file does not hot-recompile either.

Meanwhile I updated the basic template to Fable 1.0.14 and it still hot-recompiled correctly, so at least it shouldn't be a Fable problem.

### Related information 

The environment is a minimal VM I'm setting up for web and cloud development, to avoid all the annoyances with Windows. These are the globally installed tools:

- Debian 8
- VS Code + Ionide
- mono 5.0.1
- .NET Core 1.0.4
- yarn 0.24.6
- node 8.1.1
- npm 5.0.3

**Comment by alfonsogarciacaro** [comment]
@piaste Could you please try again after #123 is merged? (Or you can just check out branch fable-1-1 and give it a try.)

**Comment by piaste** [comment]
@alfonsogarciacaro 

Freshly cloned the repo and run it, still no hot reloading on file save, sorry.

I added `--verbose` hoping for some clue, but there's still no output. Can you think of any kind of debug flag I could try enabling to diagnose the issue?

Also, just in case it was a webpack issue, I tried pinning `webpack` to `2.5.1` and `webpack-dev-server` to `2.4.5` (the versions used by the default Fable template, which works) - no luck.

**Comment by alfonsogarciacaro** [comment]
@piaste Strange, if I'm not mistaken nobody else has reported problems with hot reloading so I guess it's working for most users :/

Maybe you can try adding some logs (with `console.log`) to the fable-loader when it's being run by Wepback ([here](https://github.com/fable-compiler/Fable/blob/964db2017e681104a082eb6d985725f611e6f68a/src/typescript/fable-loader/index.js#L97))? If you don't see the log it means Webpack is not detecting the change and is not making the request to fable-loader. If you do see the log you can try adding more logs at different points to see if something is failing before or after fable-loader sends the request to the Fable daemon.

In your repo, fable-loader should be in `node_modules/fable-loader/index.js`.

**Comment by piaste** [comment]
@alfonsogarciacaro 

Thanks, I will try that. I don't get that problem on Windows either so it really has to be something with the setup (so much for making a 'clean and neat' dev environment... 😄 )

**Comment by piaste** [comment]
> Maybe you can try adding some logs (with console.log) to the fable-loader when it's being run by Wepback (here)? If you don't see the log it means Webpack is not detecting the change and is not making the request to fable-loader.

I've done that and apparently it's Webpack that isn't notifying Fable of file changes (not even with `--watch-poll` option), so I'm closing this issue for now.
