### ISSUE TITLE
Login is not shown

### ISSUE THREAD

**Issue by psiLearn** [fable-compiler/fable-suave-scaffold#126]
I have a rather small problem, after logging out the second time, I need to click on home before the login screen is shown.

So the steps to reproduce:
click “Logout”, -> Welcome page is shown
click “Login” -> Login page shown, logging in
click “Logout” -> click Login welcome page is still shown 
I have to click “Home” and then “Login” again to display the Login page.

If I open a new page and open localhost:8080, it is also after the second “Logout”, that I have to press “home” before the login is displayed.

I can reproduce it with Chrome Version 59.0.3071.115  (64-Bit)
and IE Version 11.0.9600.18665.

It is not big issue for me, but I know some people who think,  if that does not work what is with the rest.

**Comment by bentayloruk** [comment]
I have just confirmed this issue on the latest `master` branch.  I put a console log in the `urlUpdate` function, and it shows that `urlUpdate` is not called after the subsequent URL change to `#login`.  Maybe an issue in the `toNavigable` feature?

**Comment by alfonsogarciacaro** [comment]
Any hint about this? @forki @et1975

**Comment by et1975** [comment]
There was a browser-specific issue with certain event not firing, but I worked around that, so this is something new. One could setup a breakpoint [here](https://github.com/fable-elmish/browser/blob/master/src/navigation.fs#L71) and see if the events get fired and handled as expected.

**Comment by bentayloruk** [comment]
I just tried to break where you suggested, but I only seem to be able to set a breakpoint [on this line](https://github.com/fable-elmish/browser/blob/master/src/navigation.fs#L74).  This breakpoint is not hit when clicking the Login after logging out (i.e. when the problem occurs).  However, if I then click Home, it is, then if I click Login again, it is.  Obviously, with this breakpoint, I can't see if there is a `lastLocation` issue.

This is the first time I've tried the JS/FS source maps.  Should I be able to get the breakpoint you suggest to be set?  Wondering if my config is borked, or if this is normal.

**Comment by bentayloruk** [comment]
Correction, I can set the breakpoint on [the line you suggest](https://github.com/fable-elmish/browser/blob/master/src/navigation.fs#L71), but it never breaks there, despite then breaking in the second match expression.

**Comment by bentayloruk** [comment]
Managed to set the breakpoint via the JS in `bundle`.  Looks to me like the location is not updated to `#wishlist` after the first login page change.  Therefore, when we log out, the first case is matched, as the `#login` location is the same as `lastLocation`.

**Comment by et1975** [comment]
Ah, I see now. Yes, `modifyUrl` doesn't trigger the event. This is intentional, I think `newUrl` should be used in most cases, with fallback to `modifyUrl` when replacing invalid route.

**Comment by alfonsogarciacaro** [comment]
About breakpoints, source maps are not perfect so sometimes they're tricky. I usually use "assert false" when I need the debugger to stop at a specific point in the F# code.

**Comment by bentayloruk** [comment]
Ah right, that makes sense.  Also, I hacked in `newUrl` and it worked.

**Comment by bentayloruk** [comment]
@alfonsogarciacaro thanks for the tip.  I also found I could get them set, if I set them from the JS bundle.

**Comment by bentayloruk** [comment]
@et1975 I wasn't sure what you meant about replacing invalid state with `modifyUrl` (and what the use cases might be), but MDN also has a [good example of usage](https://developer.mozilla.org/en/docs/Web/API/History_API#The_replaceState()_method) which helped.

**Comment by bentayloruk** [comment]
@et1975 do you think it would be useful to log the `newUrl` and `modifyUrl` details to the console, when in debug, or would it be too much noise?  Feels like this is something that could catch people out again.

**Comment by et1975** [comment]
Hm, yes more noise would be a concern, maybe this needs to be highlighted in the docs...

**Comment by bentayloruk** [comment]
@et1975 thanks for your help with this.  I'd like to try and help with the docs too, if I can.

**Comment by et1975** [comment]
@bentayloruk thank you for taking time to investigate and fix this, look forward to the docs PR 👍
