### ISSUE TITLE
Unit tests missing

### ISSUE THREAD

**Issue by aprooks** [fable-compiler/fable-suave-scaffold#128]
Since it's  scaffold I'd expect it to have unit tests projects separate from UITests.

I could add backend test example via expecto but no idea how to deal with it on Fable side. 

What do you think?

**Comment by alfonsogarciacaro** [comment]
We want to create a test library/layer for Fable with an API similar to Expecto but it's not done yet. However, it's not difficult to use any JS test library with F# code, see for example [Fable.PowerPack tests](https://github.com/fable-compiler/fable-powerpack/blob/b035313b7376922446d51e503ef2913ef41d2172/tests/PromiseTests.fs#L9-L32).

**Comment by aprooks** [comment]
Thanks, I will start with [easy] backend-side UT for now.

**Comment by aprooks** [comment]
I seem to have found a way of running tests and server via single watch: https://github.com/aspnet/DotNetTools/pull/275/files#diff-a055dfae715500c275a4f05108c9362c will try it later.

**Comment by aprooks** [comment]
Server side is fine. I will need more time to work with Fable and sort out some good example.

I was thinking of making a starter test on model transitions like @forki  mentioned on his talks about React native. Something like 

```
Given Model
|> When message 
|> Then (fun (cmd,changedModel) ->
    assert.equals changedModel.Page  NewPage
)
```
