### ISSUE TITLE
Restore on OSX doesn't work

### ISSUE THREAD

**Issue by mastoj** [fable-compiler/fable-suave-scaffold#14]
### Description

The project fail to build because of an error in the target.

### Repro steps

Check out with on OSX and try to build.

### Expected behavior

The project should build.

### Actual behavior

It doesn't build. Had 

### Known workarounds

Change this command: https://github.com/fable-compiler/fable-suave-scaffold/blob/master/.paket/Paket.Restore.targets#L10 to use mono on OSX.

**Comment by forki** [comment]
Can you please submit a patch to the corresponding file in paket and in the sample? Thx

**Comment by mastoj** [comment]
Done :)
