### ISSUE TITLE
Race condition between server watch processes

### ISSUE THREAD

**Issue by rmunn** [fable-compiler/fable-suave-scaffold#141]
### Description

I've been encountering IOExceptions pretty often while trying out the scaffold, and I think I've narrowed it down to the changes introduced in #129: there are two dotnet watch processes running, and when I change a file in the server code, they both try to generate the `src/Server/bin/Debug/netcoreapp1.1/Server.runtimeconfig.json` file at the same time, resulting in one of them throwing an IOException and shutting down.

### Repro steps

1. Clone the https://github.com/fable-compiler/fable-suave-scaffold repo.
2. Run `./build.sh run` in the freshly-cloned repo.
3. Wait for it to build and start the two `dotnet watch` processes.
4. Edit the `src/Server/WebServer.fs` file and save it.
5. One of the two `dotnet watch` processes is very likely to throw an IOException.

### Expected behavior

The watch processes should not interfere with each other, or there should be just a single watch process.

### Actual behavior

One of the two watch processes throws an `IOException` with the error message:

> System.IO.IOException: The process cannot access the file '/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/bin/Debug/netcoreapp1.1/Server.runtimeconfig.json' because it is being used by another process. [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]

Full exception stack trace:

```text
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly. [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018: System.IO.IOException: The process cannot access the file '/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/bin/Debug/netcoreapp1.1/Server.runtimeconfig.json' because it is being used by another process. [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteRuntimeConfig(ProjectContext projectContext) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
/home/rmunn/.local/share/dotnetcore/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(129,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]

The build failed. Please fix the build errors and run again.
watch : Exited with error code 1
```

That same stack trace, with the `Microsoft.NET.Sdk.targets` path trimmed so it's easier to read:

```text
error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly. [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018: System.IO.IOException: The process cannot access the file '/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/bin/Debug/netcoreapp1.1/Server.runtimeconfig.json' because it is being used by another process. [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteRuntimeConfig(ProjectContext projectContext) [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/home/rmunn/code/fsharp/fable/test-scaffold/src/Server/Server.fsproj]

The build failed. Please fix the build errors and run again.
watch : Exited with error code 1
```

### Known workarounds

If I remove `unitTestsWatch` from the `Run` target in `build.fsx` so that there's only a single `dotnet watch` process running, everything goes smoothly.

### Related information 

* Operating system: **Linux Mint 18.1** (based on Ubuntu Xenial 16.04)
* Branch: **`master`**
* .NET Runtime, CoreCLR or Mono Version: **`1.0.4`**

**Comment by alfonsogarciacaro** [comment]
Thanks for tracking this down @rmunn! Could you please have a look @aprooks?

**Comment by aprooks** [comment]
@alfonsogarciacaro @rmunn #134 fixes this. We need @forki comment there and I will fix conflicts

**Comment by alfonsogarciacaro** [comment]
@aprooks Thanks for the quick reply! Sorry, I forgot about that PR 😅 I'll merge it right away!

**Comment by alfonsogarciacaro** [comment]
...well, after the conflicts are fixed ;)

**Comment by aprooks** [comment]
I have pushed merge. @rmunn  could you please check if these changes are working under Linux?

**Comment by rmunn** [comment]
I think it works, but now I'm getting a *different* error, so I can't confirm this bugfix yet as I can't yet run the scaffold. I'm on a different computer with a different .Net Core installation, and now I get the following error:

```text
  The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
    - Check application dependencies and target a framework version installed at:
        /opt/dotnet/shared/Microsoft.NETCore.App
    - The following versions are installed:
        1.0.4
        1.1.1
    - Alternatively, install the framework version '1.1.2'.
```

The `1.1.2` requirement for Microsoft.NETCore.App is coming from https://github.com/fable-compiler/fable-suave-scaffold/commit/a9b873bf98824d8e5d7ee80f49d0b0ccaadf5ad4, which was merged 13 days ago so I'm a little puzzled why I didn't encounter problems with it earlier. I'll put this in a different issue report -- but because of this new problem, I may not be able to test #134 until tomorrow when I'm back at the computer where I first reported this issue.

I'll leave this open until I can confirm the bugfix.

**Comment by alfonsogarciacaro** [comment]
Is this happening because of the server side? In Fable we solved a similar problem (also thanks to Enrico's guidance) using the `prefercliruntime` file. See https://github.com/fable-compiler/Fable/issues/961

**Comment by rmunn** [comment]
I deleted `paket.lock` and re-ran `paket install` and got the same crash, for the same reason: Microsoft.NETCore.App version 1.1.2 had shown up again in my `paket.lock` file. So I reran `paket install`, giving it the `-v` flag this time so I could try to figure out where version 1.1.2 was coming from. The only two actual *requirements* for Microsoft.NETCore.App listed in my `paket install -v` log were:

```text
     - Microsoft.NETCore.App, >= 1.0.4 (from dotnet-fable 1.1.14)
     - Microsoft.NETCore.App, >= 1.0.5 (from Microsoft.DotNet.Watcher.Tools 1.0.1)
```

However, when I grepped for where that 1.1.2 version was coming from, I found the following:

> Request 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json?semVerLevel=2.0.0' finished with: [2.0.0-preview2-25407-01 ; 2.0.0-preview1-002111-00 ; 1.1.2 ; 1.1.1 ; 1.1.0 ; 1.1.0-preview1-001100-00 ; 1.0.5 ; 1.0.5-servicing-004880-00 ; 1.0.4 ; 1.0.3 ; 1.0.1 ; 1.0.0 ; 1.0.0-rc2-3002702]

Paket has made the natural assumption that a package that bumps just *minor* dependencies will not cause problems, and has therefore specified a dependency of 1.1.2. But because I don't have 1.1.2 **globally installed** on my system, just 1.1.1, .Net Core complains. (1.1.2 has been quite successfully installed in my `packages` folder just like any other NuGet dependency, but apparently that location isn't being searched by *something* in the .Net Core process, and I don't yet know enough to know *what* is failing to search the `packages` folder).

So I explicitly added `Microsoft.NETCore.App = 1.1.1` to my `paket.dependencies` file and re-ran `paket install`, then `./build.sh run` (in a brand-new clone to make sure I didn't have any old object references hanging around). Paket obligingly grabbed Microsoft.NETCore.App 1.1.1 for me this time instead of 1.1.2, but I still got the same error, because version 1.1.2 was still being referenced in `project.assets.json`. Specifically, in `src/Server/obj/project.assets.json` and `test/ServerTests/obj/project.assets.json`.

At this point, I'm running too far past my knowledge base to dredge up any more useful information. I don't know how .Net Core generates its `project.assets.json` files. I'll post my log file from `paket install -v`, and those two `project.assets.json` files, as attachments to this issue and maybe someone else with more .Net Core experience will be able to glean useful information from them. (I'll post them as attachments because the log file, for one, is too large to post as a gist).

**Comment by rmunn** [comment]
Here's the log from my run of `paket install -v` after deleting the `paket lock` file. **WARNING!** The uncompressed file is **48.8 MiB**! Compressing it with `xz` got it down to a mere **72 KiB** (!!!). GitHub then refused the attachment because they don't allow `.xz` files (don't ask me why they don't handle a standard Unix filetype, but they don't), so I had to put the `.xz` file into a `.zip`, gaining nothing (and padding the file by about 2 KiB) in order for GitHub to accept it.

[log-from-paket-install-no-lockfile.txt.xz.zip](https://github.com/fable-compiler/fable-suave-scaffold/files/1156550/log-from-paket-install-no-lockfile.txt.xz.zip)

Again, **WARNING:** this file is 48.8 MiB when uncompressed.

**Comment by forki** [comment]
Microsoft.NETCore.App comes from the sdk as well and AFAIK there is no way for paket to influence that. It's a serious flawed in the design. I already reported that to vf# but at this point I doubt anyone except us cares.

**Comment by rmunn** [comment]
And here are the two `project.assets.json` files I got after explicitly specifying version 1.1.1 of NETCore.App: one from `src/Server/obj/` and one from `test/ServerTests/obj/`.

[both-assets-files.zip](https://github.com/fable-compiler/fable-suave-scaffold/files/1156568/both-assets-files.zip)

**Comment by rmunn** [comment]
@forki - Where is the report? I'll chime in with another report of how this is screwing things up for me. The squeaky wheel gets the grease, after all, and I think they need to know about how this design is causing problems. If they don't get complaints (VERY polite complaints) they might think that everything's fine.

**Comment by forki** [comment]
I think we need to raise it with dotnet itself and only using nuget

**Comment by forki** [comment]
If you could create a minimal repro showing that issue then we have better chances. Nobody is understanding  paket.exe over there.

**Comment by rmunn** [comment]
I don't understand NuGet, so I'm going to run into a few practical difficulties creating that repro. Any tips?

**Comment by rmunn** [comment]
Probably relevant: https://www.hanselman.com/blog/TheMysteryOfDotnetWatchAndMicrosoftNETCoreAppVersion110preview100110000WasNotFound.aspx

**Comment by forki** [comment]
Ok try the following;

* create a new c# netcore app 
* look which packages it draws into assets file
* find one that has a closed version range and where you can find something incompatible on nuget org 
* add that package to the csproj with normal PackageReference xml tag and add pin it to the version that doesn't match the one that comes with the Microsoft.NETCore.App 

Now run dotnet restore again and investigate the assets file. 

Personally I think it should have told you about the error. 
But IIRC it will just ignore your settings from the csproj and use what the sdk wants

**Comment by forki** [comment]
@rmunn please let me know if you want to help me on this front

**Comment by rmunn** [comment]
Power outage at the office today (transformer blew) so couldn't do anything about this. I'll ping you if I do need help.

**Comment by rmunn** [comment]
Working on verifying this issue since that's what I first started with, and there's yet **another** weird exception this time. Running `./build.sh run` in a freshly-cloned copy of the scaffold repo, I get the error "The "ResolvePackageDependencies" task failed unexpectedly", with the exception:

> System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<NuGet.Packaging.Core.PackageDependency> NuGet.ProjectModel.LockFileTargetLibrary.get_Dependencies()'

I never got this error before either. I have to go work on something else just now, but I'll try to post a new issue about this one, since it's *probably* unrelated. But this does mean that I *still* can't confirm that merging https://github.com/fable-compiler/fable-suave-scaffold/pull/134 fixed this for me on Linux. I **think** it did, but I haven't yet been able to get a clean run to confirm for sure.

**Comment by rmunn** [comment]
That MissingMethodException I'm getting looks like the one over at https://github.com/OmniSharp/omnisharp-vscode/issues/1495#issuecomment-302751595. He's using .NET Core SDK 2.0.0-preview2 and so am I, so maybe I should try to remove that and install .NET Core SDK 2.0.0-preview1 or something in the .NET Core SDK 1.x series instead.

I really have not had a good experience with .NET Core so far. I'd expect moving from preview1 to preview2 not to break MAJOR things like the package manager (NuGet is the apparent source of the MissingMethodExceptions here) in any sensible project -- but by that definition, it appears that .NET Core is not sensible. Oh well, this is not the right place to rant about .NET Core. I'll try to downgrade my .NET Core installation on this machine to a .NET Core 1.x SDK version, and see if I can **finally** confirm this bug as fixed with that approach.

**Comment by rmunn** [comment]
Okay, removing the `dotnet-sdk-2.0.0-preview2-006497` package from my Linux box and installing the `dotnet-dev-1.0.4` package finally made everything work for me. So I can **finally** confirm that this bug is fixed.

The other errors I had are apparently caused by trying to run two different versions of .NET Core on my system: one installed globally, and the other one downloaded by the `build.fsx` script in this scaffold. Apparently that's a recipe for **pain** and should be avoided. Now I know.

I'll close this issue since it is actually fixed. The other problems I encountered, I'll report in the appropriate repos once I can get a good repro for them.
