### ISSUE TITLE
React as default dependency

### ISSUE THREAD

**Issue by zpodlovics** [fable-compiler/fable-suave-scaffold#143]
### Description

The Apache Project explicitly disallowed the React usage in Apache Projects due licensing problems. What is the project owners and private / corporate contributors opinion about this? As far as I know most of the F# open source project prefer Apache Licence 2.0, even if this project use a different license called unlicense.

https://issues.apache.org/jira/browse/LEGAL-303?focusedCommentId=16088663&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16088663

**Comment by forki** [comment]
We won't sue Facebook. So we're probably fine

Am 22.07.2017 12:18 nachm. schrieb "Zoltan Podlovics" <
notifications@github.com>:
