### ISSUE TITLE
Minor change needed for scaffold to build against Suave 2.2.x

### ISSUE THREAD

**Issue by rmunn** [fable-compiler/fable-suave-scaffold#145]
### Description

The recent release of Suave 2.2.x includes a [breaking change](https://github.com/SuaveIO/suave/commit/2375fdd5da6289a09ec35359d12bc38420d31c54) that, among other things, hides the `YoLo.fs` file from user code (so its functions are only exposed internally to Suave, and not to end-user code that consumes the Suave library).

This causes one line of the scaffold to break: in [`Auth.fs`](https://github.com/fable-compiler/fable-suave-scaffold/blob/7defd4d7380b7fcff60a4afd8c6d628feb90ce72/src/Server/Auth.fs#L9), there's a function that uses `UTF8.bytes`:

```fsharp
let UNAUTHORIZED s = unauthorized (UTF8.bytes s)
```

`UTF8.bytes` comes from `YoLo.fs`, so it's not accessible once you move to Suave 2.2.0 or later. The fix is to replace that line with:

```fsharp
let UNAUTHORIZED (s : string) = unauthorized (System.Text.Encoding.UTF8.GetBytes s)
```

Alternately, since the `unauthorized` and `UNAUTHORIZED` functions are already defined in `Suave.RequestErrors`, they could simply be deleted from `Auth.fs`, making the solution even simpler.

**Comment by forki** [comment]
Can you please send a pull request?

**Comment by rmunn** [comment]
Running out of time today, but will try to get to it soon (tomorrow, hopefully).

**Comment by rmunn** [comment]
Okay, PR #146 should fix this.
