### ISSUE TITLE
Getting `error MSB4057: The target "Restore" does not exist in the project.` 

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/fable-suave-scaffold#157]
### Description

Getting `error MSB4057: The target "Restore" does not exist in the project.` while dotnet restore run for projects. Same is true for server and client project.

### Repro steps

Please provide the steps required to reproduce the problem

1. Clone project.
2. Run `build.cmd` and it will work until it reaches `InstallServer` and fail with above error while trying `dotnet restore`. 
3. I tried to go to the folder and run `dotnet restore`. Same result.
### Expected behavior
It should build and test should run.
Please provide a description of the behavior you expect.

### Actual behavior

Failing at `dotnet restore`

### Known workarounds

Nothing yet.

### Related information 

OS : Win10
VS : 2017 installed with latest update
dot net  core : sdk installed 2.0.0 latest one

Note : If I try creating separate F# project using `dotnet new` then `dotnet restore` & `dotnet build` both works. In above case even build is failing. While googling I found out that in some cases build is working just restore is failing. 

Let me know if any further info is require or if there is any steps I can try to narrow down issue.

**Comment by alfonsogarciacaro** [comment]
This seems to happen after upgrading Paket if you have some old artifacts in the `obj` folders. Can you try running `git clean -xfd` and then building again?

**Comment by kunjee17** [comment]
@alfonsogarciacaro are you sure you are from this planet... Issue solved and working like charm. Thanks :)

**Comment by forki** [comment]
/cc @matthid one for our know issues knowledge base

Am 08.09.2017 4:23 vorm. schrieb "Kunjan" <notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
@kunjee17 Well, my atoms actually come from the stars, but that's the case for all of us :wink:

**Comment by matthid** [comment]
yes apparently nuget doesn't delete old msbuild files from "Fsharp.NET.Sdk" this is quite interesting...
