### ISSUE TITLE
BuildClient failure

### ISSUE THREAD

**Issue by skolkerom** [fable-compiler/fable-suave-scaffold#159]
There is build error on step BuildClient when I was trying to freshly cloned repo: 

> Module build failed: Error: The given path's format is not supported

Then I added some logging to build.fsx script to see working directory when the error occur.
Here is output:

![image](https://user-images.githubusercontent.com/3188412/30239175-711118c8-955f-11e7-8ff7-68ce0d65b393.png)

Working dir (C:\Programming\ElmishApp\src\Client) seems like to be correct.

`C:\Programming\ElmishApp>dotnet --version
2.0.0`

**Comment by alfonsogarciacaro** [comment]
Hmm, strange. The build is passing in AppVeyor (Windows). Is this with latest changes in the repo? Can you try running `dotnet fable webpack --verbose` in `src/Client` dir?

**Comment by skolkerom** [comment]
Yes, it's with the latest changes.
The same result with the --verbose option:

![image](https://user-images.githubusercontent.com/3188412/30239851-51f60d50-956d-11e7-9842-f61a74952e80.png)

**Comment by skolkerom** [comment]
Just now tried to do the next steps:
1. Clone current master branch 
2. Run build.cmd

Result is the same.

**Comment by alfonsogarciacaro** [comment]
Looking at the stack trace, it seems the error happen when accessing some of Fable libraries that should likely be in the Nuget cache. Do you happen to have the Nuget cache in a network location or similar?

**Comment by skolkerom** [comment]
You are right!
I have local nuget package cache.
I've done the following: https://stackoverflow.com/questions/30933277/how-to-clear-nuget-package-cache-using-command-line and all is ok now! 
Thanks.
