### ISSUE TITLE
The library 'hostpolicy.dll' required to execute the application was not found

### ISSUE THREAD

**Issue by davidpodhola** [fable-compiler/fable-suave-scaffold#17]
### Description

After I `pull` and `build.cmd`, I get this error 

`The library 'hostpolicy.dll' required to execute the application was not found`

### Repro steps

Please provide the steps required to reproduce the problem

0. Have correct prerequisities (.NET Core Preview4)

1. Clone the repository

2. Run `build.cmd`, 

### Expected behavior

To start the server and browser

### Actual behavior

Server is not started.

### Known workarounds

Sorry, not found.

### Related information 

* Operating system: Windows 10 Enterprise  Version 10.0.14393
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: `dotnet --version` is 1.0.0-preview4-004233
* Performance information, links to performance testing scripts: none

![capture](https://cloud.githubusercontent.com/assets/436605/22193213/16e2e5ae-e13a-11e6-906e-783861552709.PNG)

**Comment by davidpodhola** [comment]
Will want to look into this later today, just reporting in case someone else would also experience the same.

**Comment by alfonsogarciacaro** [comment]
Sorry, we need to write a proper readme for this, but actually preview4 is not the requirement, it is preview5 which is not released yet. So you need to download the latest bits: https://github.com/dotnet/cli#installers-and-binaries

**Comment by forki** [comment]
Latest bits are for rc4 and I want to put that into the build process today

Am 23.01.2017 09:43 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by davidpodhola** [comment]
OK I used the latest form the [link](https://github.com/fable-compiler/fable-suave-scaffold/issues/17#issuecomment-274429001) and it seems to be `1.0.0-rc4-004711` (also shown at the GitHub page mentioned). Not sure it is `preview5`.

Anyway I got `No executable found matching command "dotnet-compile-fsc"`.

Please advise, thanks!

![capture](https://cloud.githubusercontent.com/assets/436605/22487350/4ced8800-e80d-11e6-9ff3-7dfdc813b733.PNG)

**Comment by alfonsogarciacaro** [comment]
Hmm, that's strange. I can build the project also with `1.0.0-rc4-004711` on Windows 10. Maybe @enricosada can provide some insight?

**Comment by enricosada** [comment]
As a note for everyone (@forki @alfonsogarciacaro ) please use always released version. Latest is rc3 see https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md . Dev version (like rc4), are nightly, and can give issues.

Anyway let me try locally

**Comment by enricosada** [comment]
same for me, i can build it.

@davidpodhola can you please try

- `dotnet --version` from cmd
- `C:\Users\%USERNAME%\AppData\Local\dotnetcore\dotnet --version`
- `dotnet build src\Server\Server.fsproj -v d`
- check if `C:\Users\%USERNAME%\.nuget\packages\dotnet-compile-fsc\1.0.0-preview2-020000` exists

**Comment by alfonsogarciacaro** [comment]
I just installed RC3, but you may need to uninstall RC4 to prevent it gets precedence. You can use `Programs and Features` but I also had to delete manually the folder in `C:\Program Files\dotnet\sdk`

**Comment by forki** [comment]
https://github.com/fable-compiler/fable-suave-scaffold/blob/master/build.fsx#L29

^^ this is where decide which version is used

**Comment by davidpodhola** [comment]
- `dotnet --version` from cmd: **`1.0.0-preview2-003131`**
- `C:\Users\%USERNAME%\AppData\Local\dotnetcore\dotnet --version`: **`The system cannot find the path specified.`
- `dotnet build src\Server\Server.fsproj -v d`: **`Specify --help for a list of available options and commands. Unrecognized option '-v'`**
- check if `C:\Users\%USERNAME%\.nuget\packages\dotnet-compile-fsc\1.0.0-preview2-020000 `exists: yes, **`C:\Users\david.podhola\.nuget\packages\dotnet-compile-fsc\1.0.0-preview2-020000\dotnet-compile-fsc.1.0.0-preview2-020000.nupkg `** exists

**Comment by forki** [comment]
the build script should use the one from the sdkPath where we downloaded it: https://github.com/fable-compiler/fable-suave-scaffold/blob/master/build.fsx#L34

**Comment by enricosada** [comment]
Ok got it. 
Probably build script dont add dotnetsdk directory ti `PATH`

But i'll fix it in fsharp.net.sdk, because is not necessary to have it in that case, so better fix it for everyone

**Comment by enricosada** [comment]
In msbuild target i do `dotnet compile-fsc` without full location of dotnet used to run the fsproj. Usually is the one in path, so is ok. 
 That explain why fails, use the wrong one, preview2 Who is json based and dont see the cli tool dotnet-compile-fsc

**Comment by enricosada** [comment]
As a note, please use rc3 https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md in this repo and others (not rc4), because i am sending some breaking changes to fsproj template (easy to fix, but dont know exactly when they will be included in rc4).

**Comment by davidpodhola** [comment]
thanks @enricosada, yes, if I install rc3, it works. Anyway it seems it download rc4 too (?).

**Comment by enricosada** [comment]
@davidpodhola yes as @forki said in https://github.com/fable-compiler/fable-suave-scaffold/issues/17#issuecomment-276722444, the build script downloaded the bleeding edge rc4 (maybe a PR should change that 😄 )
