### ISSUE TITLE
[Question] Do we want to promote the usage of Suave.AspNetCore as a best practice?

### ISSUE THREAD

**Issue by Banashek** [fable-compiler/fable-suave-scaffold#4]
Right now, the scaffold uses Suave.AspNetCore as a dependency to run the suave application with kestrel as the webserver.

Kestrel has a lot of support and is very quick, which is a good thing.

But I'm not sure about the implications that this has on a larger application.

My only concern stems from https://github.com/dustinmoris/Suave.AspNetCore#error-handling-and-other-suave-config-settings

> Suave.AspNetCore allows you to hook a Suave web application (WebPart) into the ASP.NET Core pipeline. Anything that was configured in the SuaveConfig was web server specific and required to run Suave's own web server via startWebServer. In ASP.NET Core there are other means to configure the same settings. For more information please check out the ASP.NET Core Fundamentals.

So we possible lose some suave config, but gain some aspnet kestrel config? Has anyone tried hooking up logary, or other working suave config settings to make sure that the api surface is similar/compatible. 

While I don't doubt that Kestrel is a really good web server, I just want to make sure it is the right precedent to be setting, since it's possible to run suave on aspnet core without kestrel, and keep all of the configuration in the suave webserver.

**Comment by haf** [comment]
In my opinion there's no need for Kestrel and I applaud @Banashek for bringing it up.

**Comment by alfonsogarciacaro** [comment]
I'm in favour of keeping things as simple as possible in the scaffold/template. Please correct me if I'm wrong @Banashek, but I don't see anything in the code to run AspNetCore so I guess the dependency is not actually being used and we can just remove it.

**Comment by Krzysztof-Cieslak** [comment]
Yeah, as far as I can notice it's starting Suave normally...

BTW, the face when people release full project with NuGet packages for the stuff I've hacked months ago and didn't do anything with it since it was not worth effort

![](http://i.giphy.com/HXpPBrz0vwgPS.gif)

**Comment by Banashek** [comment]
Ah right my mistake on the actual usage of the library. I saw the dependency and a Program.fs and jumped to conclusions. Well at least the question was answered in the abstract then!

**Comment by forki** [comment]
I think the dependency was in banashek's original sample and I put it in
paket.dependencies and paket.references. Not sure if it is still used.

Am 21.01.2017 01:47 schrieb "Banashek" <notifications@github.com>:
