### ISSUE TITLE
Default build script fails

### ISSUE THREAD

**Issue by dogwith1eye** [fable-compiler/fable-suave-scaffold#47]
### Build script fails when running sh ./build.sh

Of course i didn't read the documentation when running the build for the first time and received the following error when the build got to the Tests.sln file.

1) Building /Users/databox/Github/fable-suave-scaffold/Tests.sln failed with exitcode 1.
2) : /Users/databox/Github/fable-suave-scaffold/test/UITests/UITests.fsproj(0,0): /Users/databox/Github/fable-suave-scaffold
/test/UITests/UITests.fsproj: Field 'System.Text.RegularExpressions.Regex.IsMatch' not found.

Upon rereading the instructions, I see that I was supposed to run the build with the "run" target for "development mode" and that the default build is for full Visual Studio on Windows users.

I would suggest rethinking this strategy, as users don't expect the default build script to fail. Maybe a simple app for VS Code users without sln files and simple core only fsproj files? And an advanced app for Visual Studio on Windows users where there is built in tooling for sln and fsproj files?

**Comment by forki** [comment]
https://github.com/fable-compiler/fable-suave-scaffold/pull/43 shows we already try to solve this issue.

**Comment by forki** [comment]
solved. Please retry
