### ISSUE TITLE
Restore failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by ThomasBoettcherHolschen** [fable-compiler/fable-suave-scaffold#58]
### Description
Restore failed on Ubuntu 16.04 with Error : 

Starting Target: Build (==> BuildClient)
/home/thomas/.local/share/dotnetcore/dotnet restore
Failed to initialize CoreCLR, HRESULT: 0x80131500
Running build failed.
Error:
System.Exception: Restore failed
  at FSI_0005.Build+clo@181-22.Invoke (Microsoft.FSharp.Core.Unit _arg4) <0x41a5b050 + 0x0017b> in <filename unknown>:0 
  at Fake.TargetHelper+targetFromTemplate@195[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x419de900 + 0x00023> in <filename unknown>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) <0x419d3a00 + 0x000ca> in <filename unknown>:0 

### Repro steps

Please provide the steps required to reproduce the problem

1. Clone Repository

2. run build.sh

### Expected behavior

Build without errors :-) 

### Known workarounds

Install http://packages.ubuntu.com/de/trusty/amd64/libicu52/download

### Related information 

* Operating system : Ubuntu 16.04.2 LTS
* Branch : Master
* CoreCLR : https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004771/dotnet-dev-ubuntu-x64.1.0.0-rc4-004771.tar.gz 
* Mono Version : Mono JIT compiler version 4.2.1

**Comment by forki** [comment]
@enricosada any ideas? Is that an issue with dotnetcore itself?

**Comment by enricosada** [comment]
That's cli related usually.

Please create a repro (`dotnet new console -lang f#`, `dotnet restore`) and post the issue in dotnet/cli repro, they can help more

**Comment by ThomasBoettcherHolschen** [comment]
thanks for the quick help... after installing this (http://packages.ubuntu.com/de/trusty/amd64/libicu52/download) I can create new app using cli without problem.
