### ISSUE TITLE
Deploy to Azure

### ISSUE THREAD

**Issue by davidpodhola** [fable-compiler/fable-suave-scaffold#59]
More of question than issue. Any ideas how to deploy to Azure? I assume content of `Server\bin\Debug\netcoreapp1.1` together with the `Client` needs to be deployed, but I will ask first before I will dig deeper into this :-)

**Comment by forki** [comment]
this is an excellent question.

If you look into the build.fsx you will see that everything is prepared to push to docker hub.
If you have a release.cmd with corresponding credentials that will actually already work.

Unfortunately azure app services are not ready to be restartet when someone pushes to docker hub.
I'm currently trying to communicate with Microsoft about that case.

In our production environment we therefor use a linux VM on azure and just scp the deploy folder over to the machine and run a bit of SSH vodoo to restart the service. That part is not in this build script here.

I'm open for other ideas 

/cc @dsyme

**Comment by davidpodhola** [comment]
Stupid question. Could [Suave.AspNetCore](https://github.com/SuaveIO/Suave.AspNetCore) be used as an alternative?

**Comment by davidpodhola** [comment]
Or how do you deploy it to http://fable-suave.azurewebsites.net ?

**Comment by alfonsogarciacaro** [comment]
@davidpodhola There seems to be some problems with Suave.AspNetCore, check #4

**Comment by davidpodhola** [comment]
Thanks @alfonsogarciacaro, I would just be interested how to deploy to Azure App Service, http://fable-suave.azurewebsites.net suggests (?) it can be deployed this way.

**Comment by alfonsogarciacaro** [comment]
It's been a while since I haven't touched Azure or any other cloud service, but I'd say @forki just replied to that question above.

**Comment by davidpodhola** [comment]
No, he says he runs the application in a machine. I can do this now too, e.g. on Windows VM in Azure.

I would be interested to run the application as an Azure App Service e.g. like

```
dotnet new -t web
dotnet restore
dotnet run
dotnet publish
```

and then FTP uploading to the `site/wwwroot`. This way you do not need to take care of the OS on the host.

**Comment by forki** [comment]
No we run this sample in app services.

(my original production app that was inspiration for this sample runs in a
VM)

We can deploy this very easily to azure app services. The only issue is
that we didn't find a way yet to restart the app service after we deployed
a new container

Am 24.02.2017 22:42 schrieb "David Podhola" <notifications@github.com>:

**Comment by davidpodhola** [comment]
OK, sorry for all the confusion, I admit I am still using the pre-stone-age tools on Azure so that is why I am asking all this.

Could you please give me a hint how to deploy to azure app service exactly the same way you did the sample? Because I tried following the way you deploy C# sample and it did not work.

All this is because I would really want to try to use this scaffold for our very next project soon.

Again, thanks a lot for the great work and sorry if I am asking stupid questions :-)

**Comment by forki** [comment]
1) create docker hub account
2) use credentials in build.fsx
3) run "build.cmd deploy"
This should create a docker image and push it to docker hub

4) point azure app services to you docker hub

Am 25.02.2017 8:55 vorm. schrieb "David Podhola" <notifications@github.com>:

**Comment by davidpodhola** [comment]
Thanks. Looks like `docker` is not able to pull my image, but that is no way related to your guide.

Anyway I [tried with net461](https://github.com/fable-compiler/fable-suave-scaffold/issues/25) and for now that is enough for me.
