### ISSUE TITLE
F# web stack - server-side rendering?

### ISSUE THREAD

**Issue by Overlord-Zurg** [fable-compiler/fable-suave-scaffold#67]
This looks awesome. I am excited to try it out sometime soon. I've been doing something very similar, sharing the domain model in .fs files referenced by both Fable .fsx and ASP.NET. The whole thing makes for a very appealing developer experience.

One question, and I'm not even sure if I'm asking it right, but I wanted to try to start a conversation:

**Does the F# web stack have any support for server-side rendering?**

(e.g. what PHP or ASP.NET Razor do (I think)?)

I don't have any specific need for it, and I'm honestly not familiar at all with the interaction between server-side rendering and single-page-app-type design, as I haven't yet done any non-toy work with SPAs - but it's obviously something that's very widely used in the world, and it's really the only gap I see in the pure F# web development story.

I'm also not that familiar with Suave, so I don't know whether this is part of what it offers, and if so how the server-side-rendering part would interact with Fable.

Curious to hear your thoughts, and keep up the awesome work!

**Comment by alfonsogarciacaro** [comment]
@Overlord-Zurg Thanks a lot for your kind words! This repository targets mainly Single Page Applications so most of the rendering is done in the client. However, if you want to do server rendering Suave offers several options, you can use [DoLiquid](https://suave.io/dotliquid.html) or use Suave's [own template engine](https://theimowski.gitbooks.io/suave-music-store/content/en/views.html) (still in experimental stage).

If you're asking for something like "isomorphic" rendering, that is, render on the server for the first request and on the client after everything is downloaded with the same DSL, there's nothing like that at the moment. Although it's something we would like to explore in the future.
