### ISSUE TITLE
"Address already in use" when doing a change in server code 

### ISSUE THREAD

**Issue by mastoj** [fable-compiler/fable-suave-scaffold#71]
I wanted to try out how the reload of both client and server worked and it failed when changing server code. I did a minor change to `defaultWishList` to get something visual out, but when it tried to reload the server it seemed like the old process were still alive since it got a conflict on the address.

## Repro steps:

* ./build.sh run
* login
* Do a minor change to `defaultWishList`
* Failed 

## Info

* Operating system : OSX
* Branch : master
* Dotnet info:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

Let me know if anything more is needed.

**Comment by forki** [comment]
do you have another service on that port? Did it start suave correctly on "build.sh run" ?
Can you please check if ports 8080 and 8085 are ok? One is suave and the other is webpack dev server

**Comment by mastoj** [comment]
It did start up fine the first time and I could go to the wish list page, but after I changed the code I got the conflict. If I would have something running on any of 8080 or 8085 I would have got a conflict when it started the first time, but I didn't.

**Comment by mastoj** [comment]
the webpack dev seems to work as expected, but the API dies.

**Comment by forki** [comment]
(yes but errors on startup are not really goo to see here)

The question is why dotnet run --watch doesn't kill the old service

2017-03-15 10:47 GMT+01:00 Tomas Jansson <notifications@github.com>:

**Comment by mastoj** [comment]
Is it anything I can run to get some more info?

**Comment by forki** [comment]
I dunno.

2017-03-15 10:50 GMT+01:00 Tomas Jansson <notifications@github.com>:

**Comment by mastoj** [comment]
I'll see if I find some time later this week or next week to figure it out, now back to java land... :/

**Comment by mastoj** [comment]
Looks like it is `dotnet`, I'll register a bug in dotnet tomorrow and put a link here to it. I ran it manually without success. When running it manually it didn't even try to do a re-run, and when killed it with `ctrl-c` the port was still bound to the port for a while so I couldn't do a restart right away.

**Comment by enricosada** [comment]
the `dotnet run --watch` command doesnt exits.

@mastoj if your issue is with `dotnet watch`, open an issue in https://github.com/aspnet/DotNetTools because watch is an external tool.

**Comment by mastoj** [comment]
Opened this issue: https://github.com/aspnet/DotNetTools/issues/278

Althought, I'm not 100 % sure it is a dotnet issue. It might be that chrome is holding on to the ports because the app does reload correctly if I don't visit a page.
