### ISSUE TITLE
add vscode files to exclude build artifacts from vscode

### ISSUE THREAD

**Issue by chinwobble** [fable-compiler/fable-suave-scaffold#84]
There are current build artifacts such as bin and obj folders are still included in vscode.

We should include a workspace config files to exclude these folders. Most of the exclusions can just be copied from .gitignore file. 

Thoughts?

**Comment by alfonsogarciacaro** [comment]
I'm a bit concerned about adding IDE-specific config files to the repo, as each user has its preferences. For example, I sometimes check the project.assets.json file in the obj folder to see that actual versions of the packages downloaded (thought it's true this is not necessary with the paket.lock). But it could also make the life easier for new users fo VSCode, so I'll let others decide :)

**Comment by chinwobble** [comment]
You make some good points.
However I feel the purpose of a scaffold is to help users get started as quickly as possible on a particular stack with some opinions on the folder structure of code, what tools to use (bundling with webpack in this case) and so on.

**Comment by alfonsogarciacaro** [comment]
Hmm, I still think that tools like Webpack are not the same as an IDE and more specifically IDE-configuration, but I acknowledge that sharing the .vscode config files will make it easier for beginners to start working with the project.

If @forki has no other comment, could you please send a PR to add the .vscode config files @chinwobble ? Thanks a lot in advance!
