### ISSUE TITLE
Add CSS pre-processor (LESS / SASS) to project

### ISSUE THREAD

**Issue by chinwobble** [fable-compiler/fable-suave-scaffold#88]
How do you guys feel about using less or sass CSS-frameworks which is common in most modern web projects? 
Is it too distracting trying add too many things to the scaffold?

**Comment by alfonsogarciacaro** [comment]
Hmm, I personally like LESS and use the less-loader in my projects, but on the other hand it's true than trying to add too many things (we could also add the typescript-loader in case someone needs it, etc...) makes the config files more bloated an increases the space and time needed to download the npm dependencies.

Maybe adding a section to the README explaining how to add additional Webpack loaders would be a good compromise?
