### ISSUE TITLE
Catalog of reasons Mono/.NET Framework is needed

### ISSUE THREAD

**Issue by dsyme** [fable-compiler/fable-suave-scaffold#92]
I took a look over the repo.  It's looking great.  Moving to the 1.0 SDK of .NET Core really helped

Could we track the reasons why Mono or .NET Framework are needed and link to any WIP issues in the relevant repos?

* [ ] FAKE needs Mono or .NET Framework
* [ ] Paket needs Mono or .NET Framework
* [ ] Canopy needs Mono or .NET Framework

I'm just wondering what's remaining to lift that dependency.  

thanks
don

**Comment by forki** [comment]
Yes. Nobody knows how to move the tools to dotnetcore properly. It seems to be hard.

**Comment by alfonsogarciacaro** [comment]
Probably better to wait until netstandard 2.0 is released. Then we don't need to worry about polyfilling all the missing APIs.

**Comment by forki** [comment]
It's not even the APIs - we basically did that part.
It's that FAKE and Paket use so many hacks to work properly. Like bootstrapping, hosting FCS, ...
And then you can't even open netcore projects in VS - how should all my 250 contributors keep up the good work!?

The whole .NET core story only works for web properly - it's a fact

**Comment by alfonsogarciacaro** [comment]
Fable 1.0 is a netcore app and hosts FCS. Also, according to Phil around July VS should be able to open the new .fsproj :pray:

I think it can be done, but possibly we'll save pain just by waiting a bit more :)

**Comment by forki** [comment]
July is super optimistic and would require that people are "active on the topic" (sorry @cartermp could not resist)

**Comment by alfonsogarciacaro** [comment]
After fsharpX we've decided that we are all a super optimistic community and we love each other so much ;)

**Comment by forki** [comment]
yeah - just honesty is also important

**Comment by dsyme** [comment]
I'm ok to wait however long, i just want to catalog what we're waiting for :)

**Comment by cartermp** [comment]
Just for visbility, VS work for F# .NET Core projects is tracked here: https://github.com/dotnet/project-system/issues?q=is%3Aopen+is%3Aissue+label%3AArea-F%23

**Comment by alfonsogarciacaro** [comment]
Closing in favor of #149, we can track the global requirements (and how to minimize them) there :+1:
