### ISSUE TITLE
build.sh fail on Ubuntu

### ISSUE THREAD

**Issue by parthmshukla** [fable-compiler/fable-suave-scaffold#93]
Not able to do setup properly

Error log: 

https://gist.github.com/parthmshukla/af569f011a106f5157d805ec53466be6

### Related information 
* Ubuntu
* Mono JIT compiler version 4.8.0

@forki Please look into this.

**Comment by forki** [comment]
It looks like phantom is not behaving. trying https://github.com/fable-compiler/fable-suave-scaffold/pull/94

**Comment by forki** [comment]
can you please try again on master?

**Comment by parthmshukla** [comment]
It's working...
