### ISSUE TITLE
Cursor jumps to end when editing

### ISSUE THREAD

**Issue by sandeepc24** [fable-compiler/fable-suave-scaffold#99]
Go to login page and type "12345" now position the cursor after "2" and type "7", the cursor jumps after "5".

### Related information 

* Windows 10
* Master
* .CoreCLR

**Comment by et1975** [comment]
It used to be the case, but it's it reproducible in the current code base? I've switched the `input` to use `DefaulValue` instead of `Value` and it should behave at this point.

**Comment by sandeepc24** [comment]
Apologies for the late reply, switching to DefalutValue fixes this issue.
